namespace AssetProvenanceHelper.Core.Generation;

public sealed record GenerationItemRecord(
    string ManifestFingerprint,
    string RequestKey,
    string AssetName,
    string FileName,
    GenerationMode Mode,
    string ProviderId,
    string Model,
    string Quality,
    int TargetWidth,
    int TargetHeight,
    int GenerationWidth,
    int GenerationHeight,
    string CustomId,
    GenerationItemStatus Status,
    DateTimeOffset SubmittedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    int SchemaVersion = 1,
    string? ProviderRequestId = null,
    string? ProviderBatchId = null,
    string? BatchId = null,
    string? StagedOutputPath = null,
    string? RawSha256 = null,
    string? NormalizedSha256 = null,
    string? ErrorCode = null,
    string? ErrorMessage = null,
    string? CandidateId = null,
    string? ProviderRawPath = null,
    DateTimeOffset? ProviderOutputReceivedAtUtc = null,
    bool ProviderOutputReceived = false);
